### PR TITLE
Update ff-peers.nix

### PR DESCRIPTION
**Pull request by sp33dy**
Crazy Career pool

### CODE REVIEW

**Comment by johnalotoski** [comment]
Hi @sp33dy -- both these nodes appear to be down, or at least a firewall is preventing comms with the port. Please open up these nodes and we'll get them added with the next group, thanks.

**Comment by sp33dy** [comment]
Any idea how I can get that tested? I've got a laptop that could tether to mobile to be off my network. Is there any node software i could install on it to test the connectivity to diagnose?

The node is installed in VirtualBox with Ubuntu. I've configured ufw and have:

To                         Action      From
--                         ------      ----
8081                       ALLOW IN    Anywhere                  
8082                       ALLOW IN    Anywhere                  

8081                       ALLOW OUT   Anywhere                  
8082                       ALLOW OUT   Anywhere

Configured, with portforwarding to the host machine. The host machine is win 10 and I've configured McAfee for those ports. Finally I have a router that port forwards correctly. I can test that the ports are forwarded.  Just wondering what I can use to diagnose what is the cause?? Any thoughts?

**Comment by sp33dy** [comment]
I've just tethered and used telnet. Port 8081 was connecting, but 8082 was not. I've just turned ufw off on the virtualbox and both now connect. I've then toggled Mcafee on and off and can see it works when on with the rule. Can you try again for me please?

**Comment by johnalotoski** [comment]
Both ports close out the TCP connection immediately regardless of originating conn location; there is still an issue with these.  A great place for support in resolving a technical issue like this would be the telegram Cardano StakePool Workgroup channel where a number of operators will be happy to help you diagnose and resolve the issue: https://t.me/CardanoStakePoolWorkgroup

**Comment by sp33dy** [comment]
Thanks, I believe I've discovered what the problem is! I've changed ports in the process. Going to close this pull request and raise a new one with new details.

**Pull request closed without merging**
